// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamGovIntegration.Api.Data;

#nullable disable

namespace SamGovIntegration.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260509051901_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SamGovIntegration.Api.Models.ContractAwardEntity", b =>
                {
                    b.Property<string>("Piid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AwardeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AwardeeUei")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateFetched")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentOrAgency")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DescriptionOfRequirement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DollarsObligated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FetchBatchId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NaicsCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProductOrServiceCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SolicitationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceEndpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Piid");

                    b.HasIndex("ApprovedDate");

                    b.HasIndex("AwardeeUei");

                    b.HasIndex("NaicsCode");

                    b.HasIndex("ApprovedDate", "DollarsObligated");

                    b.ToTable("ContractAwards");
                });

            modelBuilder.Entity("SamGovIntegration.Api.Models.FetchBatchEntity", b =>
                {
                    b.Property<string>("BatchId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateRangeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRangeStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("MaxDollarAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinDollarAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalRecordsFetched")
                        .HasColumnType("int");

                    b.Property<int>("TotalRecordsStored")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("Status");

                    b.ToTable("FetchBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
